# Generated by Django 3.2 on 2024-03-01 18:15

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaluser',
            name='name',
        ),
        migrations.AddField(
            model_name='medicaluser',
            name='encryptedName',
            field=encrypted_model_fields.fields.EncryptedCharField(default='waste'),
            preserve_default=False,
        ),
    ]
